services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    volumes:
      - .:/var/www/html
      - ./log:/var/www/html/log
      - ./temp:/var/www/html/temp
      - ./migrations:/var/www/html/migrations
    depends_on:
      - db

  web:
    image: nginx:1.27
    container_name: web-server
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./default_nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pwd123
      MYSQL_DATABASE: simple_product_administration
      MYSQL_USER: db_user
      MYSQL_PASSWORD: pwd123
    volumes:
      - db_data:/var/lib/mysql

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8081:8080"

volumes:
  db_data:
